/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminVisitorsRouteImport } from './routes/admin/visitors'
import { Route as AdminResponsesRouteImport } from './routes/admin/responses'
import { Route as AdminNewsletterRouteImport } from './routes/admin/newsletter'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminChatbotRouteImport } from './routes/admin/chatbot'
import { Route as AdminApplicationsRouteImport } from './routes/admin/applications'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisitorsRoute = AdminVisitorsRouteImport.update({
  id: '/admin/visitors',
  path: '/admin/visitors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResponsesRoute = AdminResponsesRouteImport.update({
  id: '/admin/responses',
  path: '/admin/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/admin/newsletter',
  path: '/admin/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChatbotRoute = AdminChatbotRouteImport.update({
  id: '/admin/chatbot',
  path: '/admin/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/admin/applications',
  path: '/admin/applications',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/schemes': typeof SchemesRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/schemes': typeof SchemesRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/schemes': typeof SchemesRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/chatbot': typeof AdminChatbotRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/responses': typeof AdminResponsesRoute
  '/admin/visitors': typeof AdminVisitorsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/schemes'
    | '/services'
    | '/terms'
    | '/admin/applications'
    | '/admin/chatbot'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/responses'
    | '/admin/visitors'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/schemes'
    | '/services'
    | '/terms'
    | '/admin/applications'
    | '/admin/chatbot'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/responses'
    | '/admin/visitors'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/schemes'
    | '/services'
    | '/terms'
    | '/admin/applications'
    | '/admin/chatbot'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/newsletter'
    | '/admin/responses'
    | '/admin/visitors'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SchemesRoute: typeof SchemesRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminChatbotRoute: typeof AdminChatbotRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminResponsesRoute: typeof AdminResponsesRoute
  AdminVisitorsRoute: typeof AdminVisitorsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visitors': {
      id: '/admin/visitors'
      path: '/admin/visitors'
      fullPath: '/admin/visitors'
      preLoaderRoute: typeof AdminVisitorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/responses': {
      id: '/admin/responses'
      path: '/admin/responses'
      fullPath: '/admin/responses'
      preLoaderRoute: typeof AdminResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/admin/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chatbot': {
      id: '/admin/chatbot'
      path: '/admin/chatbot'
      fullPath: '/admin/chatbot'
      preLoaderRoute: typeof AdminChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SchemesRoute: SchemesRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminChatbotRoute: AdminChatbotRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminResponsesRoute: AdminResponsesRoute,
  AdminVisitorsRoute: AdminVisitorsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
